import type { SiteLocale } from "../i18n/locales";

const en = {
  navHome: "Home",
  navTools: "More tools",
  navBlog: "Blog",
  navPricing: "Pricing",
  menuFoot: "12 tools, all free to use",
  blogTitle: "Getting more from AI text tools",
  blogSub: "How-to guides, real use cases and comparisons to help you get each tool right.",
  blogTagsL: ["All", "Guides", "Use cases", "Comparisons"],
  posts: [
    {
      tag: 1,
      title: "How to read a research paper in 5 minutes with AI summaries",
      desc: "Get the findings and method first, then decide what deserves a close read.",
      date: "2026-09-18",
      read: "6 min",
    },
    {
      tag: 1,
      title: "Three rewrite tones and when to use each",
      desc: "Formal, casual, concise — the right tone matters more than the right words.",
      date: "2026-09-04",
      read: "4 min",
    },
    {
      tag: 2,
      title: "E-commerce: translate listings into many languages at once",
      desc: "Keep selling points and terminology intact, without the machine-translated feel.",
      date: "2026-08-27",
      read: "5 min",
    },
    {
      tag: 2,
      title: "Turn a rough draft into a clean work email",
      desc: "Switch between formal and friendly in one click.",
      date: "2026-08-12",
      read: "3 min",
    },
    {
      tag: 3,
      title: "AI Summarizer vs a general chatbot for long reads",
      desc: "One 8,000-word report, two approaches: time and quality compared.",
      date: "2026-07-30",
      read: "7 min",
    },
    {
      tag: 1,
      title: "Keeping technical terms intact when translating",
      desc: "Work in sections and build a glossary first — three tips for sharper translations.",
      date: "2026-07-15",
      read: "4 min",
    },
  ],
  search: "Search tools",
  login: "Log in",
  ctaStart: "Get started",
  themeTip: "Toggle theme",
  langSwitch: "中文",
  badge: "",
  h1a: "Paste text.",
  h1b: "Rewrite, summarize or translate instantly.",
  heroSub: "Free · No sign-up · Text never stored",
  crumbHome: "Home",
  crumbTools: "Tools",
  optT: {
    rewrite: "Tone",
    summarize: "Length",
    translate: "Into",
  },
  inPh: "Paste or type your text here…",
  chars: "chars",
  sample: "Sample text",
  clear: "Clear",
  run: "Run",
  running: "Working…",
  again: "Regenerate",
  output: "Result",
  stIdle: "Waiting",
  stRun: "Generating",
  stDone: "Done",
  outEmpty: "Your result streams in here. No text handy? Try “Sample text”.",
  copy: "Copy",
  copied: "Copied",
  sec: "s",
  outChars: "chars",
  trust: ["No account needed", "Text never stored or used for training", "40+ languages"],
  toolsEyebrow: "Toolbox",
  toolsTitle: "More tools",
  viewAll: "Browse all tools",
  casesEyebrow: "Use cases",
  casesTitle: "What people use it for",
  readGuide: "Read the guide",
  cases: [
    {
      tag: "Students · Research",
      title: "Read a paper in 5 minutes",
      desc: "Get the findings and method first, then decide which sections deserve a close read.",
    },
    {
      tag: "E-commerce",
      title: "Translate listings into many languages",
      desc: "Keep selling points and terminology intact, without the machine-translated feel.",
    },
    {
      tag: "Workplace",
      title: "Turn a rough draft into a clean email",
      desc: "Switch between formal and friendly in one click — less time agonizing over wording.",
    },
  ],
  faqTitle: "Questions, answered",
  faq: [
    [
      "Do I need an account?",
      "No. Every core tool works right away. Sign in to keep your history and get a higher daily limit.",
    ],
    [
      "Is my text stored?",
      "No. Text is used only for the current request, discarded right after, and never used for training.",
    ],
    [
      "What are the free plan limits?",
      "20 runs per day, up to 3,000 characters each. Pro is unlimited, up to 20,000 characters per run.",
    ],
    [
      "Can my team use it together?",
      "Yes. Create a workspace, invite members and assign Owner, Admin or Member roles, with one shared bill.",
    ],
  ],
  ctaTitle: "Working with text every day? There is a faster way.",
  ctaSub: "Start free. Upgrade any time.",
  ctaBtn: "Create a free account",
  fTag: "A set of small AI tools for people who work with words every day.",
  rights: "Privacy · Terms · Cookies",
  fCols: [
    {
      h: "Popular tools",
      l: ["AI Rewriter", "AI Summarizer", "AI Translator", "All tools"],
    },
    {
      h: "Resources",
      l: ["Blog", "Pricing", "Changelog"],
    },
    {
      h: "Legal",
      l: ["Privacy policy", "Terms of service", "Cookie policy"],
    },
  ],
  howTitle: "Three steps",
  how: [
    {
      n: 1,
      t: "Paste your text",
      d: "Up to 3,000 characters, or drop a .txt file straight in.",
    },
    {
      n: 2,
      t: "Pick a mode and option",
      d: "Tone for rewrites, length for summaries, target language for translation.",
    },
    {
      n: 3,
      t: "Copy the result",
      d: "Output streams in live. Not quite right? Regenerate.",
    },
  ],
  relatedTitle: "Related tools",
  dirEyebrow: "All tools",
  dirTitle: "Find the right one",
  dirSub: "Filter by category or search. Every tool is free and works instantly.",
  dirSearch: "Search by name or purpose…",
  noResult: "No matching tools. Try another keyword.",
  guideCrumb: "Guides",
  guideTitle: "How to read a research paper in 5 minutes with AI summaries",
  guideMeta: "6 min read · Updated Sep 2026",
  guideIntro:
    "For most papers you only need three answers: what problem it tackles, how, and whether the conclusion holds. Reading a summary first — then deciding whether to invest an hour — is the most time-efficient order.",
  gStepsTitle: "The three-step method",
  gSteps: [
    {
      n: "1",
      t: "Locate with “One line”",
      d: "Paste the abstract and intro to get a one-sentence version. If it does not match your question, skip the paper.",
    },
    {
      n: "2",
      t: "Break it down with “Bullets”",
      d: "Paste the methods and experiments to get 3–5 bullets and judge whether the design holds up.",
    },
    {
      n: "3",
      t: "Close-read only what matters",
      d: "Use the bullets to jump back to the figures and sections you actually need.",
    },
  ],
  tipTitle: "Tip: work section by section",
  tipBody: "Pasting one section at a time gives sharper bullets than the whole paper at once.",
  tryNow: "Open AI Summarizer",
  cmpTitle: "How it compares",
  cmp: [
    ["", "Toolsmith", "Manual reading", "General chatbot"],
    ["Average time", "~1 min", "30–60 min", "3–5 min"],
    ["Prompt writing", "Not needed", "—", "Required"],
    ["Output format", "Line / bullets / paragraph", "—", "Depends on prompt"],
    ["Text stored", "Never", "—", "Depends on service"],
  ],
  tocTitle: "On this page",
  toc: ["Why summary first", "The three-step method", "How it compares", "FAQ"],
  sideCtaTitle: "Try it now",
  sideCtaBody: "Paste an abstract and see how much fits in one sentence.",
  priceEyebrow: "Pricing",
  priceTitle: "Start free. Upgrade when you need to.",
  priceSub:
    "Every plan includes every tool. Plans differ only in limits, length and team features.",
  monthly: "Monthly",
  yearly: "Yearly",
  popular: "Most popular",
  perMonth: "/ mo",
  perSeat: "/ seat / mo",
  plans: [
    {
      name: "Free",
      desc: "Enough for occasional use.",
      cta: "Get started",
      feats: ["20 runs per day", "Up to 3,000 characters", "All 12 tools"],
    },
    {
      name: "Pro",
      desc: "For people who write every day.",
      cta: "Upgrade to Pro",
      feats: [
        "Unlimited runs",
        "Up to 20,000 characters",
        "History and favorites",
        "Priority queue",
      ],
    },
    {
      name: "Team",
      desc: "Small teams that need shared billing.",
      cta: "Create a workspace",
      feats: [
        "Everything in Pro",
        "Multiple workspaces and invites",
        "Owner / Admin / Member roles",
        "Shared billing and usage",
      ],
    },
  ],
  palPh: "Search tools…",
  palNav: "navigate",
  palOpen: "open",
  langLabel: "Language",
  soon: "Soon",
};
const zh = {
  navHome: "首页",
  navTools: "更多工具",
  navBlog: "博客",
  navPricing: "定价",
  menuFoot: "12 款工具，全部免费使用",
  blogTitle: "用好 AI 文本工具",
  blogSub: "使用指南、真实场景与工具对比，帮你把每个工具用到位。",
  blogTagsL: ["全部", "使用指南", "使用场景", "对比"],
  posts: [
    {
      tag: 1,
      title: "如何用 AI 摘要在 5 分钟内读完一篇论文",
      desc: "先抓结论和方法，再决定哪些章节值得精读。",
      date: "2026-09-18",
      read: "6 分钟",
    },
    {
      tag: 1,
      title: "AI 改写的三种语气，分别什么时候用",
      desc: "正式、轻松、简洁——用对语气，比改对字更重要。",
      date: "2026-09-04",
      read: "4 分钟",
    },
    {
      tag: 2,
      title: "跨境电商：商品描述一次翻成多种语言",
      desc: "保留卖点与术语，避免机翻腔，直接上架。",
      date: "2026-08-27",
      read: "5 分钟",
    },
    {
      tag: 2,
      title: "把草稿改成一封得体的工作邮件",
      desc: "一键切换正式或友好语气，少花时间斟酌措辞。",
      date: "2026-08-12",
      read: "3 分钟",
    },
    {
      tag: 3,
      title: "AI 摘要 vs 通用聊天机器人：读长文哪个更快",
      desc: "同一篇 8,000 字报告，两种方式的用时与结果对比。",
      date: "2026-07-30",
      read: "7 分钟",
    },
    {
      tag: 1,
      title: "翻译时如何保留专业术语",
      desc: "分段处理、先建术语表，三个小技巧让译文更准确。",
      date: "2026-07-15",
      read: "4 分钟",
    },
  ],
  search: "搜索工具",
  login: "登录",
  ctaStart: "免费开始",
  themeTip: "切换明暗",
  langSwitch: "EN",
  badge: "",
  h1a: "粘贴文字，",
  h1b: "立即改写、摘要或翻译",
  heroSub: "免费 · 无需注册 · 文本不存储",
  crumbHome: "首页",
  crumbTools: "工具",
  optT: {
    rewrite: "语气",
    summarize: "长度",
    translate: "译为",
  },
  inPh: "在这里粘贴或输入文本…",
  chars: "字",
  sample: "示例文本",
  clear: "清空",
  run: "开始处理",
  running: "处理中…",
  again: "重新生成",
  output: "结果",
  stIdle: "等待输入",
  stRun: "生成中",
  stDone: "已完成",
  outEmpty: "结果会实时出现在这里。没有文本？点「示例文本」试试。",
  copy: "复制",
  copied: "已复制",
  sec: "秒",
  outChars: "字",
  trust: ["无需注册", "文本不存储、不用于训练", "支持 40+ 语言"],
  toolsEyebrow: "工具箱",
  toolsTitle: "更多工具",
  viewAll: "查看全部工具",
  casesEyebrow: "使用场景",
  casesTitle: "别人都用它来做什么",
  readGuide: "阅读指南",
  cases: [
    {
      tag: "学生 · 科研",
      title: "5 分钟读完一篇论文",
      desc: "先用摘要抓住结论和方法，再决定哪些章节值得精读。",
    },
    {
      tag: "跨境电商",
      title: "商品描述一次翻成多种语言",
      desc: "保留卖点与术语，避免机翻腔，直接上架。",
    },
    {
      tag: "职场沟通",
      title: "把草稿改成得体的邮件",
      desc: "一键切换正式或友好语气，减少反复斟酌的时间。",
    },
  ],
  faqTitle: "常见问题",
  faq: [
    [
      "需要注册才能使用吗？",
      "不需要。所有基础工具打开即用；登录后可以保存历史记录，并获得更高的每日额度。",
    ],
    ["我输入的文本会被保存吗？", "不会。文本只用于当次处理，完成后立即丢弃，也不会用于训练模型。"],
    [
      "免费版有什么限制？",
      "免费版每天 20 次处理，单次最多 3,000 字。Pro 不限次数，单次最多 20,000 字。",
    ],
    [
      "可以和团队一起使用吗？",
      "可以。创建工作区后邀请成员，按 Owner / Admin / Member 三种角色分配权限，账单统一管理。",
    ],
  ],
  ctaTitle: "每天都要处理文字？换个更快的方式。",
  ctaSub: "免费版即可开始，随时升级。",
  ctaBtn: "免费创建账号",
  fTag: "为每天和文字打交道的人准备的一组 AI 小工具。",
  rights: "隐私政策 · 服务条款 · Cookie 政策",
  fCols: [
    {
      h: "热门工具",
      l: ["AI 改写", "AI 摘要", "AI 翻译", "全部工具"],
    },
    {
      h: "资源",
      l: ["博客", "定价", "更新日志"],
    },
    {
      h: "法律",
      l: ["隐私政策", "服务条款", "Cookie 政策"],
    },
  ],
  howTitle: "三步完成",
  how: [
    {
      n: 1,
      t: "粘贴文本",
      d: "支持最多 3,000 字，也可以直接拖入 .txt 文件。",
    },
    {
      n: 2,
      t: "选择模式与选项",
      d: "改写选语气、摘要选长度、翻译选目标语言。",
    },
    {
      n: 3,
      t: "复制结果",
      d: "结果逐字生成，不满意可以直接重新生成。",
    },
  ],
  relatedTitle: "相关工具",
  dirEyebrow: "全部工具",
  dirTitle: "找到合适的那一个",
  dirSub: "按类别筛选或直接搜索。每个工具都免费、打开即用。",
  dirSearch: "搜索工具名称或用途…",
  noResult: "没有匹配的工具，换个关键词试试。",
  guideCrumb: "使用指南",
  guideTitle: "如何用 AI 摘要在 5 分钟内读完一篇论文",
  guideMeta: "阅读约 6 分钟 · 更新于 2026-09",
  guideIntro:
    "大多数论文你只需要知道三件事：它解决了什么问题、用了什么方法、结论是否可信。先读摘要，再决定要不要投入一个小时精读，是最省时间的阅读顺序。",
  gStepsTitle: "三步阅读法",
  gSteps: [
    {
      n: "1",
      t: "用「一句话」模式定位",
      d: "把摘要和引言粘贴进来，得到一句话版本。如果这句话和你的问题无关，可以直接跳过这篇。",
    },
    {
      n: "2",
      t: "用「要点」模式拆结构",
      d: "把方法和实验部分粘贴进来，得到 3–5 条要点，快速判断实验设计是否站得住。",
    },
    {
      n: "3",
      t: "只精读值得的部分",
      d: "根据要点回到原文，只读你真正需要的图表和章节。",
    },
  ],
  tipTitle: "小技巧：分段处理效果更好",
  tipBody: "一次粘贴一个章节，比整篇丢进去得到的要点更准确。",
  tryNow: "打开 AI 摘要",
  cmpTitle: "和其他方式比一比",
  cmp: [
    ["", "Toolsmith", "手动精读", "通用聊天机器人"],
    ["平均用时", "约 1 分钟", "30–60 分钟", "3–5 分钟"],
    ["需要写提示词", "不需要", "—", "需要"],
    ["输出格式可控", "一句话 / 要点 / 段落", "—", "取决于提示词"],
    ["文本是否存储", "不存储", "—", "取决于服务"],
  ],
  tocTitle: "本文目录",
  toc: ["为什么先读摘要", "三步阅读法", "和其他方式比一比", "常见问题"],
  sideCtaTitle: "现在就试试",
  sideCtaBody: "粘贴一段论文摘要，看看一句话能说清多少。",
  priceEyebrow: "定价",
  priceTitle: "先免费用，需要时再升级",
  priceSub: "所有方案都包含全部工具。区别只在额度、长度和团队功能。",
  monthly: "按月",
  yearly: "按年",
  popular: "最受欢迎",
  perMonth: "/ 月",
  perSeat: "/ 人 / 月",
  plans: [
    {
      name: "免费",
      desc: "偶尔用用，足够了。",
      cta: "开始使用",
      feats: ["每天 20 次处理", "单次最多 3,000 字", "全部 12 款工具"],
    },
    {
      name: "Pro",
      desc: "每天都和文字打交道的个人。",
      cta: "升级 Pro",
      feats: ["不限处理次数", "单次最多 20,000 字", "历史记录与收藏", "优先处理队列"],
    },
    {
      name: "团队",
      desc: "需要统一管理与账单的小团队。",
      cta: "创建工作区",
      feats: [
        "包含 Pro 全部功能",
        "多工作区与成员邀请",
        "Owner / Admin / Member 权限",
        "统一账单与用量",
      ],
    },
  ],
  palPh: "搜索工具…",
  palNav: "选择",
  palOpen: "打开",
  langLabel: "语言",
  soon: "即将支持",
} satisfies typeof en;
export const toolsmithCopies = { en, "zh-CN": zh };
export function toolsmithCopy(locale: SiteLocale) {
  return toolsmithCopies[locale];
}
