import type { SiteLocale } from "../i18n/locales";

const en = {
  loginTab: "Log in",
  registerTab: "Sign up",
  authTitleLogin: "Welcome back",
  authTitleReg: "Create your account",
  authSubLogin: "Log in to see your history and workspaces.",
  authSubReg: "We will create a default workspace for you automatically.",
  name: "Name",
  email: "Email",
  password: "Password",
  forgot: "Forgot password?",
  submitLogin: "Log in",
  submitReg: "Create account",
  agree: "By continuing you agree to our Terms of Service and Privacy Policy.",
  brandLine: "One account, many workspaces, clear permissions.",
  brandPts: [
    "Email and password sign-in, secure sessions",
    "Join as many workspaces as you need",
    "Owner, Admin and Member roles",
  ],
  seats: "seats",
  ws: ["Overview", "Members", "Usage", "Settings"],
  signOut: "Sign out",
  wsMembers: "Members",
  wsMembersSub: "Invite teammates to the workspace and assign their roles.",
  invitePh: "Teammate email — press Enter to invite",
  invite: "Send invite",
  colMember: "Member",
  colRole: "Role",
  colJoined: "Joined",
  remove: "Remove",
  you: "You",
  pending: "Pending",
  matrixTitle: "Role permissions",
  matrixSub: "Three fixed roles, permissions at a glance.",
  perms: [
    "View workspace and use tools",
    "View member list",
    "Invite and remove members",
    "Change member roles",
    "Manage billing and plan",
    "Delete workspace",
  ],
  invited: "Invite sent to ",
  removed: "Member removed",
  roleChanged: "Role updated",
};
const zh = {
  loginTab: "登录",
  registerTab: "注册",
  authTitleLogin: "欢迎回来",
  authTitleReg: "创建你的账号",
  authSubLogin: "登录后可以查看历史记录和工作区。",
  authSubReg: "注册时会自动为你创建一个默认工作区。",
  name: "姓名",
  email: "邮箱",
  password: "密码",
  forgot: "忘记密码？",
  submitLogin: "登录",
  submitReg: "创建账号",
  agree: "继续即表示你同意我们的服务条款和隐私政策。",
  brandLine: "一个账号，多个工作区，权限清清楚楚。",
  brandPts: [
    "邮箱密码登录，会话安全存储",
    "一个人可以加入多个工作区",
    "Owner、Admin、Member 三种角色",
  ],
  seats: "席位",
  ws: ["概览", "成员", "用量", "设置"],
  signOut: "退出",
  wsMembers: "成员",
  wsMembersSub: "邀请同事加入工作区，并为他们分配角色。",
  invitePh: "输入同事邮箱，按回车邀请",
  invite: "发送邀请",
  colMember: "成员",
  colRole: "角色",
  colJoined: "加入时间",
  remove: "移除",
  you: "你",
  pending: "待接受",
  matrixTitle: "角色权限",
  matrixSub: "固定的三种角色，权限一目了然。",
  perms: [
    "查看工作区与使用工具",
    "查看成员列表",
    "邀请与移除成员",
    "修改成员角色",
    "管理账单与套餐",
    "删除工作区",
  ],
  invited: "邀请已发送至 ",
  removed: "已移除成员",
  roleChanged: "角色已更新",
} satisfies typeof en;
export const toolsmithPrivateCopies = { en, "zh-CN": zh };
export function toolsmithPrivateCopy(locale: SiteLocale) {
  return toolsmithPrivateCopies[locale];
}
